PMM-6038 PT summary.
percona/pmm-agent pull request #181
Opened 2020-08-19 14:44 UTC by JiriCtvrtka

2020-08-25 05:53 UTC, BupycHuk requested changes

2020-08-25 05:53 UTC, BupycHuk commented on actions/pt_summary_action.go
> +	if err := cmd.Run(); err != nil {
we should pass
```
	pdeathsig.Set(cmd, unix.SIGKILL)
```

2020-08-25 05:53 UTC, BupycHuk commented on actions/pt_summary_action.go
> +		return nil, err
Should we return nil as result? Is it possible to have non-zero exit code but usefull output?

2020-08-25 05:53 UTC, BupycHuk commented on actions/pt_summary_action.go
> +	cmd := exec.CommandContext(ctx, "pt-summary")
Maybe it's better to extract logic related to starting, stopping and getting logs into separate structure? We will have other similar actions.

2020-08-25 05:53 UTC, BupycHuk commented on actions/pt_summary_action_test.go
> +	require.Regexp(t, regexp.MustCompile("# Percona Toolkit System Summary Report ######################"), string(res))
We can use strings.contains instead of regexp.

2020-08-25 05:53 UTC, BupycHuk commented on config/config.go
> +	PTSummary string `yaml:"pt_summary"`
let's keep it in a separate block

2020-08-25 13:24 UTC, BupycHuk requested changes

2020-08-25 13:24 UTC, BupycHuk commented on config/config_test.go
> +			"--paths-pt-summary=/usr/local/percona/pmm2/pt-summary",
let's remove it and check default value. To learn where it placed ask @EvgeniyPatlan

2020-08-25 13:24 UTC, BupycHuk commented on config/config_test.go
> +			Paths: Paths{
Let's remove it too, we should have default value

2020-08-25 13:55 UTC, BupycHuk approved these changes
Only one minor comment

2020-08-25 13:55 UTC, BupycHuk commented on client/client.go
> +				action = actions.NewProcessAction(p.ActionId, c.cfg.Paths.PTSummary, []string{})
```suggestion
				action = actions.NewProcessAction(p.ActionId, c.cfg.Paths.PTSummary, new([]string))
```

2020-08-25 14:39 UTC, AlekSi commented on client/client.go
> +				action = actions.NewProcessAction(p.ActionId, c.cfg.Paths.PTSummary, []string{})
That will not compile

2020-08-25 14:43 UTC, JiriCtvrtka commented on client/client.go
> +				action = actions.NewProcessAction(p.ActionId, c.cfg.Paths.PTSummary, []string{})
Yes, I already discard it. Thanks.

2020-08-26 09:45 UTC, JiriCtvrtka commented
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1065

2020-08-28 12:13 UTC, merged