Add defaults to the local API
percona/pmm-agent pull request #204
Opened 2020-10-26 15:58 UTC by AlekSi

2020-10-26 17:27 UTC, BupycHuk approved these changes

2020-10-26 17:29 UTC, BupycHuk requested changes
Tests are failing

2020-10-26 17:34 UTC, AlekSi commented
> reviewdog: environment variable $REVIEWDOG_GITHUB_API_TOKEN is not set

@BupycHuk indeed 😆

2020-10-26 17:44 UTC, BupycHuk commented
Interesting thing here that reviewdog was working on the parent commit.

2020-10-27 10:42 UTC, BupycHuk approved these changes

2020-10-27 10:42 UTC, merged