fix dockerhub pull limit with auth
percona/pmm-agent pull request #216
Opened 2020-12-24 21:47 UTC by atymchuk

2020-12-24 21:47 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/pmm-agent?pullRequest=216) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/pmm-agent?pullRequest=216) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/pmm-agent?pullRequest=216) it.</sub>

2020-12-24 21:59 UTC, BupycHuk approved these changes

2020-12-24 21:59 UTC, BupycHuk requested changes
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password

2020-12-25 08:45 UTC, atymchuk commented
> Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password

Forgot the braces, it seems to be working now ) https://travis-ci.com/github/percona/pmm-agent/jobs/464775195

2020-12-25 10:43 UTC, AlekSi commented
https://github.com/percona/pmm-agent/pull/217

2020-12-25 10:43 UTC, closed without merging