PMM-5778 check exporter format
percona/pmm-agent pull request #237
Opened 2021-02-18 14:17 UTC by askomorokhov

https://jira.percona.com/browse/PMM-5778

Related:
 - https://github.com/percona/pmm-managed/pull/670

2021-02-18 16:02 UTC, JiriCtvrtka approved these changes

2021-02-18 16:17 UTC, percona-csalguero approved these changes

2021-02-21 11:10 UTC, BupycHuk requested changes
Please resolve merge conflicts

2021-02-22 11:09 UTC, BupycHuk approved these changes

2021-02-22 11:17 UTC, JiriCtvrtka approved these changes

2021-02-22 11:31 UTC, percona-csalguero approved these changes

2021-02-22 16:11 UTC, merged