PMM-7676 Azure exporter integration.
percona/pmm-agent pull request #245
Opened 2021-03-17 09:32 UTC by JiriCtvrtka

2021-03-23 18:06 UTC, percona-csalguero approved these changes

2021-03-24 09:22 UTC, askomorokhov approved these changes

2021-03-25 10:51 UTC, adivinho commented on config/config_test.go
> +				AzureDatabaseExporter: "/usr/local/percona/pmm2/exporters/azure_database_exporter",
Azure exporter has got name azure_exporter
![Screenshot_20210325_124935](https://user-images.githubusercontent.com/25184101/112461491-a0dec000-8d68-11eb-8b3f-a3dfbe03263b.png)

2021-03-28 15:09 UTC, BupycHuk requested changes

2021-03-28 15:09 UTC, BupycHuk commented on config/config_test.go
> +				AzureDatabaseExporter: "/usr/local/percona/pmm2/exporters/azure_database_exporter",
^

2021-03-29 12:48 UTC, askomorokhov commented on config/config_test.go
> +				AzureDatabaseExporter: "/usr/local/percona/pmm2/exporters/azure_database_exporter",
Fixed

2021-03-31 08:51 UTC, BupycHuk approved these changes

2021-04-05 08:54 UTC, merged