PMM-7000 Do not stop agent on conn fail
percona/pmm-agent pull request #278
Opened 2021-06-22 09:21 UTC by askomorokhov

https://jira.percona.com/browse/PMM-7000

2021-06-22 12:52 UTC, percona-csalguero approved these changes

2021-06-23 10:22 UTC, JiriCtvrtka approved these changes

2021-06-27 12:27 UTC, BupycHuk requested changes

2021-06-27 12:27 UTC, BupycHuk commented on client/client.go
> +				close(c.done)
we close c.done here and don't open again.

2021-06-27 12:27 UTC, BupycHuk commented on client/client.go
> +	for {
this doesn't look thread-safe.
High possibility of running a few `process` go routines.

2021-07-06 12:19 UTC, closed without merging