PMM-8308: enrich agent info with process exec path
percona/pmm-agent pull request #314
Opened 2022-01-26 20:08 UTC by qwest812

2022-01-26 20:08 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/pmm-agent?pullRequest=314) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/pmm-agent?pullRequest=314) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/pmm-agent?pullRequest=314) it.</sub>

2022-02-07 09:13 UTC, BupycHuk approved these changes

2022-02-07 09:14 UTC, BupycHuk requested changes
Please fix tests.

2022-04-28 08:31 UTC, BupycHuk approved these changes

2022-04-28 15:56 UTC, artemgavrilov approved these changes

2022-05-18 17:35 UTC, merged