PMM-5668 add --log-level and ENV PMM_AGENT_LOG_LEVEL
percona/pmm-agent pull request #346
Opened 2022-03-24 18:06 UTC by YaroslavPodorvanov

PMM-5668

Build: SUBMODULES-2400

- [ ] Links to other linked pull requests (optional).

2022-03-24 18:13 UTC, YaroslavPodorvanov commented on config/config.go
> +	LogLevel string `yaml:"log-level"`
use "log-level" like before exists "listen-address"

2022-04-04 14:40 UTC, BupycHuk requested changes

2022-04-04 14:40 UTC, BupycHuk commented on config/logger.go
> +			// grpclog.SetLoggerV2(&gRPCLogger{Entry: logrus.WithField("component", "grpclog")})
let's remove it.

2022-04-04 14:55 UTC, BupycHuk commented on config/logger.go
> +	level, trace := parseLoggerConfig(cfg.LogLevel, cfg.Debug, cfg.Trace)
I don't see any validation for possible values, so user still can use trace and will be surprised

2022-04-04 15:01 UTC, YaroslavPodorvanov commented on config/logger.go
> +	level, trace := parseLoggerConfig(cfg.LogLevel, cfg.Debug, cfg.Trace)
> I don't see any validation for possible values, so user still can use trace and will be surprised

we have two validation:
1 in `EnumVar(&cfg.LogLevel, "debug", "info", "warn", "error", "fatal")`
2 in `parsedLevel, err := logrus.ParseLevel(level)`

2022-04-04 15:03 UTC, YaroslavPodorvanov commented
> we probably should pass value of log level to exporters, I don't see it in this PR.

Yes, but it will be in issue [PMM-7326](https://jira.percona.com/browse/PMM-7326), because we need pass "log-level" through pmm-managed in case when "log-level" used in pmm-admin

2022-04-04 15:05 UTC, BupycHuk commented on config/logger.go
> +	level, trace := parseLoggerConfig(cfg.LogLevel, cfg.Debug, cfg.Trace)
1. yeah, missed part in flag.
2. ParseLevel [supports](https://github.com/sirupsen/logrus/blob/master/logrus.go#L39) `trace`, but it doesn't matter after first point. 

anyway `trace` looks unnecessary in this context, we can just check `cfg.Trace` in that case.

2022-04-06 14:08 UTC, ritbl approved these changes

2022-04-27 14:27 UTC, merged